### ISSUE TITLE
RS232 communication with PTU

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/PSA-P2-PTU-Project#1]
Setting the communication parameters.

Testing interactively using gtkterm.

**Comment by miguelriemoliveira** [comment]
@Marcos01Sa can you please work on this?

**Comment by Marcos01Sa** [comment]
Yes

**Comment by manuelgitgomes** [comment]
Hello @miguelriemoliveira and @Marcos01Sa!

I have used a baud rate of 38400 bits/s. Can you please study if this is the most adequate one @Marcos01Sa?
