### ISSUE TITLE
Python script for PTU communication

### ISSUE THREAD

**Issue by miguelriemoliveira** [miguelriemoliveira/PSA-P2-PTU-Project#2]
The goal is to command the ptu using a python script.

**Comment by miguelriemoliveira** [comment]
@manuelgitgomes can you help?

**Comment by manuelgitgomes** [comment]
Hello! Have you tried the library `pyserial`? Have an example [here](https://www.tutorialspoint.com/how-do-i-access-the-serial-rs232-port-in-python).
