### ISSUE TITLE
How to connect to the camera and get an image

### ISSUE THREAD

**Issue by Joao-FSS** [miguelriemoliveira/PSA-P2-PTU-Project#4]
turn on camera

**Comment by miguelriemoliveira** [comment]
You should use opencv for this. An example here:

https://docs.opencv.org/3.4/dd/d43/tutorial_py_video_display.html

**Comment by manuelgitgomes** [comment]
I have created an interface using the suggestion @miguelriemoliveira gave.

**Comment by Joao-FSS** [comment]
it is working
